from setuptools import setup

setup(
        name='TomJerry',
        version='1.0',
        packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings',
                  'venv.lib.python2.7.site-packages.pgu', 'venv.lib.python2.7.site-packages.pgu.gui',
                  'venv.lib.python2.7.site-packages.pip', 'venv.lib.python2.7.site-packages.pip.req',
                  'venv.lib.python2.7.site-packages.pip.vcs', 'venv.lib.python2.7.site-packages.pip.utils',
                  'venv.lib.python2.7.site-packages.pip.compat', 'venv.lib.python2.7.site-packages.pip.models',
                  'venv.lib.python2.7.site-packages.pip._vendor',
                  'venv.lib.python2.7.site-packages.pip._vendor.distlib',
                  'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
                  'venv.lib.python2.7.site-packages.pip._vendor.colorama',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
                  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
                  'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
                  'venv.lib.python2.7.site-packages.pip._vendor.progress',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
                  'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
                  'venv.lib.python2.7.site-packages.pip._vendor.packaging',
                  'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
                  'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
                  'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
                  'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
                  'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.operations',
                  'venv.lib.python2.7.site-packages.html', 'venv.lib.python2.7.site-packages.http',
                  'venv.lib.python2.7.site-packages.past', 'venv.lib.python2.7.site-packages.past.tests',
                  'venv.lib.python2.7.site-packages.past.types', 'venv.lib.python2.7.site-packages.past.utils',
                  'venv.lib.python2.7.site-packages.past.builtins', 'venv.lib.python2.7.site-packages.past.translation',
                  'venv.lib.python2.7.site-packages.numpy', 'venv.lib.python2.7.site-packages.numpy.ma',
                  'venv.lib.python2.7.site-packages.numpy.doc', 'venv.lib.python2.7.site-packages.numpy.fft',
                  'venv.lib.python2.7.site-packages.numpy.lib', 'venv.lib.python2.7.site-packages.numpy.core',
                  'venv.lib.python2.7.site-packages.numpy.f2py', 'venv.lib.python2.7.site-packages.numpy.compat',
                  'venv.lib.python2.7.site-packages.numpy.linalg', 'venv.lib.python2.7.site-packages.numpy.random',
                  'venv.lib.python2.7.site-packages.numpy.testing', 'venv.lib.python2.7.site-packages.numpy.distutils',
                  'venv.lib.python2.7.site-packages.numpy.distutils.command',
                  'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
                  'venv.lib.python2.7.site-packages.numpy.matrixlib',
                  'venv.lib.python2.7.site-packages.numpy.polynomial', 'venv.lib.python2.7.site-packages.queue',
                  'venv.lib.python2.7.site-packages.scipy', 'venv.lib.python2.7.site-packages.scipy.io',
                  'venv.lib.python2.7.site-packages.scipy.io.arff',
                  'venv.lib.python2.7.site-packages.scipy.io.arff.tests',
                  'venv.lib.python2.7.site-packages.scipy.io.tests', 'venv.lib.python2.7.site-packages.scipy.io.matlab',
                  'venv.lib.python2.7.site-packages.scipy.io.matlab.tests',
                  'venv.lib.python2.7.site-packages.scipy.io.harwell_boeing',
                  'venv.lib.python2.7.site-packages.scipy.io.harwell_boeing.tests',
                  'venv.lib.python2.7.site-packages.scipy.odr', 'venv.lib.python2.7.site-packages.scipy.odr.tests',
                  'venv.lib.python2.7.site-packages.scipy._lib', 'venv.lib.python2.7.site-packages.scipy._lib.tests',
                  'venv.lib.python2.7.site-packages.scipy.misc', 'venv.lib.python2.7.site-packages.scipy.misc.tests',
                  'venv.lib.python2.7.site-packages.scipy.stats', 'venv.lib.python2.7.site-packages.scipy.stats.tests',
                  'venv.lib.python2.7.site-packages.scipy.linalg',
                  'venv.lib.python2.7.site-packages.scipy.linalg.tests',
                  'venv.lib.python2.7.site-packages.scipy.signal',
                  'venv.lib.python2.7.site-packages.scipy.signal.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse',
                  'venv.lib.python2.7.site-packages.scipy.sparse.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.isolve',
                  'venv.lib.python2.7.site-packages.scipy.sparse.linalg.isolve.tests',
                  'venv.lib.python2.7.site-packages.scipy.sparse.csgraph',
                  'venv.lib.python2.7.site-packages.scipy.sparse.csgraph.tests',
                  'venv.lib.python2.7.site-packages.scipy.cluster',
                  'venv.lib.python2.7.site-packages.scipy.cluster.tests',
                  'venv.lib.python2.7.site-packages.scipy.fftpack',
                  'venv.lib.python2.7.site-packages.scipy.fftpack.tests',
                  'venv.lib.python2.7.site-packages.scipy.ndimage',
                  'venv.lib.python2.7.site-packages.scipy.ndimage.tests',
                  'venv.lib.python2.7.site-packages.scipy.spatial',
                  'venv.lib.python2.7.site-packages.scipy.spatial.tests',
                  'venv.lib.python2.7.site-packages.scipy.special',
                  'venv.lib.python2.7.site-packages.scipy.special.tests',
                  'venv.lib.python2.7.site-packages.scipy.special._precompute',
                  'venv.lib.python2.7.site-packages.scipy.optimize',
                  'venv.lib.python2.7.site-packages.scipy.optimize._lsq',
                  'venv.lib.python2.7.site-packages.scipy.optimize.tests',
                  'venv.lib.python2.7.site-packages.scipy.optimize._trlib',
                  'venv.lib.python2.7.site-packages.scipy.constants',
                  'venv.lib.python2.7.site-packages.scipy.constants.tests',
                  'venv.lib.python2.7.site-packages.scipy.integrate',
                  'venv.lib.python2.7.site-packages.scipy.integrate._ivp',
                  'venv.lib.python2.7.site-packages.scipy.integrate.tests',
                  'venv.lib.python2.7.site-packages.scipy.interpolate',
                  'venv.lib.python2.7.site-packages.scipy.interpolate.tests',
                  'venv.lib.python2.7.site-packages.scipy._build_utils', 'venv.lib.python2.7.site-packages.wheel',
                  'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
                  'venv.lib.python2.7.site-packages.future', 'venv.lib.python2.7.site-packages.future.moves',
                  'venv.lib.python2.7.site-packages.future.moves.dbm',
                  'venv.lib.python2.7.site-packages.future.moves.html',
                  'venv.lib.python2.7.site-packages.future.moves.http',
                  'venv.lib.python2.7.site-packages.future.moves.test',
                  'venv.lib.python2.7.site-packages.future.moves.urllib',
                  'venv.lib.python2.7.site-packages.future.moves.xmlrpc',
                  'venv.lib.python2.7.site-packages.future.moves.tkinter',
                  'venv.lib.python2.7.site-packages.future.tests', 'venv.lib.python2.7.site-packages.future.types',
                  'venv.lib.python2.7.site-packages.future.utils', 'venv.lib.python2.7.site-packages.future.builtins',
                  'venv.lib.python2.7.site-packages.future.backports',
                  'venv.lib.python2.7.site-packages.future.backports.html',
                  'venv.lib.python2.7.site-packages.future.backports.http',
                  'venv.lib.python2.7.site-packages.future.backports.test',
                  'venv.lib.python2.7.site-packages.future.backports.email',
                  'venv.lib.python2.7.site-packages.future.backports.email.mime',
                  'venv.lib.python2.7.site-packages.future.backports.urllib',
                  'venv.lib.python2.7.site-packages.future.backports.xmlrpc',
                  'venv.lib.python2.7.site-packages.future.standard_library', 'venv.lib.python2.7.site-packages.py2app',
                  'venv.lib.python2.7.site-packages.py2app.recipes',
                  'venv.lib.python2.7.site-packages.py2app.recipes.PIL',
                  'venv.lib.python2.7.site-packages.py2app.bootstrap',
                  'venv.lib.python2.7.site-packages.py2app.converters',
                  'venv.lib.python2.7.site-packages.py2app.apptemplate',
                  'venv.lib.python2.7.site-packages.py2app.bundletemplate', 'venv.lib.python2.7.site-packages.pygame',
                  'venv.lib.python2.7.site-packages.pygame.docs', 'venv.lib.python2.7.site-packages.pygame.gp2x',
                  'venv.lib.python2.7.site-packages.pygame.tests',
                  'venv.lib.python2.7.site-packages.pygame.tests.test_utils',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.all_ok',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.exclude',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.timeout',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.failures1',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.everything',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.incomplete',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.print_stderr',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.print_stdout',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.infinite_loop',
                  'venv.lib.python2.7.site-packages.pygame.tests.run_tests__tests.incomplete_todo',
                  'venv.lib.python2.7.site-packages.pygame.threads', 'venv.lib.python2.7.site-packages.pygame.examples',
                  'venv.lib.python2.7.site-packages.winreg', 'venv.lib.python2.7.site-packages.xmlrpc',
                  'venv.lib.python2.7.site-packages._thread', 'venv.lib.python2.7.site-packages.copyreg',
                  'venv.lib.python2.7.site-packages.reprlib', 'venv.lib.python2.7.site-packages.tkinter',
                  'venv.lib.python2.7.site-packages.altgraph', 'venv.lib.python2.7.site-packages.builtins',
                  'venv.lib.python2.7.site-packages.macholib', 'venv.lib.python2.7.site-packages.ordlookup',
                  'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
                  'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages._markupbase',
                  'venv.lib.python2.7.site-packages.libfuturize', 'venv.lib.python2.7.site-packages.libfuturize.fixes',
                  'venv.lib.python2.7.site-packages.modulegraph', 'venv.lib.python2.7.site-packages.socketserver',
                  'venv.lib.python2.7.site-packages._dummy_thread', 'venv.lib.python2.7.site-packages.libpasteurize',
                  'venv.lib.python2.7.site-packages.libpasteurize.fixes',
                  'venv.lib.python2.7.site-packages.pkg_resources',
                  'venv.lib.python2.7.site-packages.pkg_resources.extern',
                  'venv.lib.python2.7.site-packages.pkg_resources._vendor',
                  'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
        url='',
        license='',
        author='Qian Wang',
        author_email='ken_qrose@mails.tsinghua.edu.cn',
        description=''
)
